tensorflow/tensorflow-lite: fix XNNPACK build for qemuarm
Issue: LIN1022-2442

...
|external/XNNPACK/src/qs8-igemm/gen/4x8c4-minmax-rndnu-aarch32-neondot-ld64.S:140:
Error: selected processor does not support `vsdot.s8 q8,q2,d0[0]' in ARM
mode
...

Does not support 32 bit ARM with Neon DotProduct

(master rev: e0efac349f2aac3d65ccbeee20475dbb1ea3dd19) -- backport

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Signed-off-by: Li Wang <li.wang@windriver.com>
Signed-off-by: Archana Polampalli <archana.polampalli@windriver.com>